server:
  port: 9090

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: measurement-service
          uri: lb://MEASUREMENT-SERVICE
          predicates:
            - Path=/api/quantity/**

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/auth/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/