server:
  port: 8081

spring:
  application:
    name: measurement-service

  datasource:
    url: jdbc:h2:mem:measurementdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

app:
  jwt:
    secret: mysecretkeymysecretkeymysecretkey12345
    expiration: 86400000