spring.application.name=QuantityMeasurementApp

# H2 DATABASE
spring.datasource.url=jdbc:h2:mem:quantitydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 CONSOLE
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# SWAGGER
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# JWT
app.jwt.secret=bridgelabzquantitymeasurementapplicationjwtsecretkey
app.jwt.expiration=86400000